[platformio]
src_dir      = .
default_envs = teensy32

[env:teensy32]
platform          = teensy
board             = teensy31
board_build.f_cpu = 120000000L
framework         = arduino
lib_deps =
    ../../../platform
    ../../../tu
    https://github.com/pedvide/ADC.git
build_flags =
    -std=gnu++17
    -Os
    -ffunction-sections
    -fdata-sections
upload_protocol = teensy-cli
upload_flags    = -s